### ISSUE TITLE
Impact on people who browse private by default

### ISSUE THREAD

**Issue by mnot** [w3ctag/private-mode#12]
Some people currently browse in private mode by default. Some parts of this spec will make doing so more "in your face" / "chatty", which may cause them to stop using private by default.

Discuss.

**Comment by hadleybeeman** [comment]
Reviewed at f2f in Nice. While we are looking at the issues of privacy on the web, we aren't standardising private mode right now. This issue should be kept/archived until such work is initiated, when the scope is more clearly defined. The repo is closed.
