### ISSUE TITLE
browsing data vs. configuration

### ISSUE THREAD

**Issue by mnot** [w3ctag/private-mode#13]
Many extensions and browser settings are driven by the user; they are not "state" as set by the site.

Some of it falls into a grey area -- e.g., HSTS information (#10), password managers (#2). 

How should this be handled? The spec needs to be a lot crisper here...

**Comment by hadleybeeman** [comment]
While we are looking at the issues of privacy on the web, we aren't standardising private mode right now. This issue should be kept/archived until such work is initiated, when the scope is more clearly defined. The repo is closed.
