### ISSUE TITLE
Extensions Private Mode

### ISSUE THREAD

**Issue by twirl** [w3ctag/private-mode#14]
Some extensions (Flash, in particular) are extremely dangerous since they provide means to identify user (Flash cookie) AND at the same time user needs them to be enabled (to play video). Probably, we should talk about enabling private mode in plugins/extensions too?

**Comment by hadleybeeman** [comment]
While we are looking at the issues of privacy on the web, we aren't standardising private mode right now. This issue should be kept/archived until such work is initiated, when the scope is more clearly defined. The repo is closed.
