### ISSUE TITLE
Taken up on 2 Nov

### ISSUE THREAD

**Issue by torgo** [w3ctag/private-mode#15]
Discussed on call 2 Nov https://github.com/w3ctag/meetings/blob/gh-pages/2015/telcons/12-02-agenda.md - presentation API people wondering what's going on with it. Some possible evidence of demand?

**Comment by hadleybeeman** [comment]
While we are looking at the issues of privacy on the web, we aren't standardising private mode right now. This issue should be kept/archived until such work is initiated, when the scope is more clearly defined. The repo is closed.
