### ISSUE TITLE
Cookie scoping

### ISSUE THREAD

**Issue by mnot** [w3ctag/private-mode#4]
... needs discussion / refinement.

**Comment by mnot** [comment]
See also: https://www.torproject.org/projects/torbrowser/design/#identifier-linkability re "double-keying."

**Comment by hadleybeeman** [comment]
Reviewed at f2f in Nice. While we are looking at the issues of privacy on the web, we aren't standardising private mode right now. This issue should be kept/archived until such work is initiated, when the scope is more clearly defined. The repo is closed.
