### ISSUE TITLE
Trust and Intermediaries

### ISSUE THREAD

**Issue by mnot** [w3ctag/private-mode#6]
... needs to be filled out.

This needs to cover trust issues around configuring proxies; they can be useful (e.g., for Tor) or harmful.

**Comment by hadleybeeman** [comment]
Reviewed at f2f in Nice. While we are looking at the issues of privacy on the web, we aren't standardising private mode right now. This issue should be kept/archived until such work is initiated, when the scope is more clearly defined. The repo is closed.
