### ISSUE TITLE
HTTP request constraints

### ISSUE THREAD

**Issue by mnot** [w3ctag/private-mode#7]
There are currently a number of constraints on the form of an HTTP request.

Is this level of precision for HTTP requests necessary? It doesn't completely address HTTP
fingerprinting, and could be a major implementation pain.

Needs implementer feedback.

**Comment by hadleybeeman** [comment]
Reviewed at f2f in Nice. While we are looking at the issues of privacy on the web, we aren't standardising private mode right now. This issue should be kept/archived until such work is initiated, when the scope is more clearly defined. The repo is closed.
