### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by mnot** [w3ctag/private-mode#8]
TBD: history, fonts, introspection, geolocation, keypress, window, WebStorage, etc.

**Comment by Ipoumb1988** [comment]
I would like to work in this project .I  can?

**Comment by hadleybeeman** [comment]
Reviewed at f2f in Nice. While we are looking at the issues of privacy on the web, we aren't standardising private mode right now. This issue should be kept/archived until such work is initiated, when the scope is more clearly defined. The repo is closed.
